# application-dev.yml

chick-site:
  mysql:
    ip: 127.0.0.1
    port: 3306
    db: blog
    username: root
    password: 123456

  mybatis-plus:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
