# application-dev.yml

chick-site:
  mysql:
    ip: 127.0.0.1
    port: 3306
    db: chick_site
    username: root
    password: 123456

  mybatis-plus:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
